// dummyEvents.js

export const dummyEvents = [
    {
        id: 1,
        title: "Cybersecurity Training",
        date: "2024-06-15",
        description: "A comprehensive training session on cybersecurity practices.",
        category: "Workshop",
        eventType: "Individual",
        hostedBy: "Cyber Team Alpha",
        capacity: 50,
        registeredTeams: 30,
        createdBy: "user123",
        eventCode: "CYBER24",
        eventLink: "https://example.com/cyber-training",
        paymentInfo: "Venmo: @CyberTeamAlpha",
        prize: "Certificate of Completion",
        additionalInfo: "Please bring your own laptop."
    },
    {
        id: 2,
        title: "Hackathon Event",
        date: "2024-07-20",
        description: "A competitive event to showcase your hacking skills.",
        category: "CTF",
        eventType: "Team",
        hostedBy: "Hack Masters",
        capacity: 100,
        registeredTeams: 85,
        createdBy: "user456",
        eventCode: "HACK24",
        eventLink: "https://example.com/hackathon",
        paymentInfo: "Bitcoin: 1ABC123...",
        prize: "$5000 for 1st place",
        additionalInfo: "Teams of 3-5 members allowed."
    },
    {
        id: 3,
        title: "Web Security Workshop",
        date: "2024-08-10",
        description: "An in-depth workshop on web security techniques.",
        category: "RvB",
        eventType: "Individual",
        hostedBy: "Security Pros",
        capacity: 75,
        registeredTeams: 60,
        createdBy: "user789",
        eventCode: "WEBSEC24",
        eventLink: "https://example.com/web-security",
        paymentInfo: "Venmo: @SecurityPros",
        prize: "Free 1-year subscription to Security+ course",
        additionalInfo: "Beginners welcome!"
    },
];